version: 0.2
phases:
  pre_build: # Add kubeconfig to access to EKS cluster
    commands:
      - "mkdir ~/.kube/"
      - aws eks update-kubeconfig --name russ-cluster
  post_build:
    commands:
      - "helm $HELM_ACTION -i node-micoservice chart/ -f ./chart/values.yaml -n node-microservice"