apiVersion: v1
kind: Service
metadata:
  name: node-microservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: node-microservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
